### ISSUE TITLE
Need a way to specify the anchor to attach to in the config

### ISSUE THREAD

**Issue by charlieyouakim** [sezzle/sezzle-js#27]
See brydge keyboards site (https://www.brydgekeyboards.com). On the cart page, our widget doesn't attach to the right section. (it's working now with our old system)

It fails on this page because it's attaching to the wrong div. Can we add in a way to specify the div to attach to the same way we specify the div to listen to?

**Comment by sanbornsen** [comment]
Having a specific element to render Sezzle's widget is a good idea, but specifying a path may fail. The target path fetches all the price elements in the page. If we provide a path like that to render the widget it'll fetch all the matching elements in the page and will render same thing in multiple places if there are multiple match. The element should always be respective to the price element. So, instead of providing a path for that, we can provide a tag or class name or id respective to the price element and we can find the closest match to the price element. 

For example, 
```
targetXPath: [
   {
      path: '.price/span'
      renderto: '.someclass'
   }
]
```
For this input, the outputs maybe - 
```
<div class="someclass price">
  <span>$212.21</span>
  ...
  <!-- Sezzle div comes here -->
</div>
```
```
<div class="price">
  <span>$212.21</span>
  <div class="someclass">
    ...
    <!-- Sezzle div comes here -->
  </div>
</div>
```
```
<div class="price">
  <span>$212.21</span>
</div>
<div class="someclass">
  ...
  <!-- Sezzle div comes here -->
</div>
```
The closest matching element to ```<span>$212.21</span>```

**Comment by charlieyouakim** [comment]
I like it!
